package com.example.presentation.di

const val RETROFIT_INSTANCE= "RETROFIT_INSTANCE"

const val DOMAIN_CURRENT_WEATHER_MAPPER = "CURRENT_WEATHER_MAPPER"
const val UI_CURRENT_WEATHER_MAPPER = "UI_CURRENT_WEATHER_MAPPER"

const val GET_WEATHER_USE_CASE = "GET_WEATHER_USE_CASE"


